module AmarcordApi.Types.JsonCreateAttributoInput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonCreateAttributoInput
instance Show JsonCreateAttributoInput
instance Eq JsonCreateAttributoInput
instance FromJSON JsonCreateAttributoInput
instance ToJSON JsonCreateAttributoInput
