-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonBeamtimeScheduleRow
module AmarcordApi.Types.JsonBeamtimeScheduleRow where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonBeamtimeScheduleRow@ in the specification.
-- 
-- 
data JsonBeamtimeScheduleRow = JsonBeamtimeScheduleRow {
  -- | chemicals
  jsonBeamtimeScheduleRowChemicals :: ([GHC.Types.Int])
  -- | comment
  , jsonBeamtimeScheduleRowComment :: Data.Text.Internal.Text
  -- | date
  , jsonBeamtimeScheduleRowDate :: Data.Text.Internal.Text
  -- | shift
  , jsonBeamtimeScheduleRowShift :: Data.Text.Internal.Text
  -- | td_support
  , jsonBeamtimeScheduleRowTdSupport :: Data.Text.Internal.Text
  -- | users
  , jsonBeamtimeScheduleRowUsers :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonBeamtimeScheduleRow
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["chemicals" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowChemicals obj] : ["comment" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowComment obj] : ["date" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowDate obj] : ["shift" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowShift obj] : ["td_support" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowTdSupport obj] : ["users" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowUsers obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["chemicals" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowChemicals obj] : ["comment" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowComment obj] : ["date" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowDate obj] : ["shift" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowShift obj] : ["td_support" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowTdSupport obj] : ["users" Data.Aeson.Types.ToJSON..= jsonBeamtimeScheduleRowUsers obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonBeamtimeScheduleRow
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonBeamtimeScheduleRow" (\obj -> (((((GHC.Base.pure JsonBeamtimeScheduleRow GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemicals")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "comment")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "date")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "shift")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "td_support")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "users"))}
-- | Create a new 'JsonBeamtimeScheduleRow' with all required fields.
mkJsonBeamtimeScheduleRow :: [GHC.Types.Int] -- ^ 'jsonBeamtimeScheduleRowChemicals'
  -> Data.Text.Internal.Text -- ^ 'jsonBeamtimeScheduleRowComment'
  -> Data.Text.Internal.Text -- ^ 'jsonBeamtimeScheduleRowDate'
  -> Data.Text.Internal.Text -- ^ 'jsonBeamtimeScheduleRowShift'
  -> Data.Text.Internal.Text -- ^ 'jsonBeamtimeScheduleRowTdSupport'
  -> Data.Text.Internal.Text -- ^ 'jsonBeamtimeScheduleRowUsers'
  -> JsonBeamtimeScheduleRow
mkJsonBeamtimeScheduleRow jsonBeamtimeScheduleRowChemicals jsonBeamtimeScheduleRowComment jsonBeamtimeScheduleRowDate jsonBeamtimeScheduleRowShift jsonBeamtimeScheduleRowTdSupport jsonBeamtimeScheduleRowUsers = JsonBeamtimeScheduleRow{jsonBeamtimeScheduleRowChemicals = jsonBeamtimeScheduleRowChemicals,
                                                                                                                                                                                                                                           jsonBeamtimeScheduleRowComment = jsonBeamtimeScheduleRowComment,
                                                                                                                                                                                                                                           jsonBeamtimeScheduleRowDate = jsonBeamtimeScheduleRowDate,
                                                                                                                                                                                                                                           jsonBeamtimeScheduleRowShift = jsonBeamtimeScheduleRowShift,
                                                                                                                                                                                                                                           jsonBeamtimeScheduleRowTdSupport = jsonBeamtimeScheduleRowTdSupport,
                                                                                                                                                                                                                                           jsonBeamtimeScheduleRowUsers = jsonBeamtimeScheduleRowUsers}
