module AmarcordApi.Types.JsonDeleteDataSetOutput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonDeleteDataSetOutput
instance Show JsonDeleteDataSetOutput
instance Eq JsonDeleteDataSetOutput
instance FromJSON JsonDeleteDataSetOutput
instance ToJSON JsonDeleteDataSetOutput
