-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonChangeRunExperimentType
module AmarcordApi.Types.JsonChangeRunExperimentType where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonChangeRunExperimentType@ in the specification.
-- 
-- 
data JsonChangeRunExperimentType = JsonChangeRunExperimentType {
  -- | beamtime_id
  jsonChangeRunExperimentTypeBeamtimeId :: GHC.Types.Int
  -- | experiment_type_id
  , jsonChangeRunExperimentTypeExperimentTypeId :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | run_internal_id
  , jsonChangeRunExperimentTypeRunInternalId :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonChangeRunExperimentType
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["beamtime_id" Data.Aeson.Types.ToJSON..= jsonChangeRunExperimentTypeBeamtimeId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("experiment_type_id" Data.Aeson.Types.ToJSON..=)) (jsonChangeRunExperimentTypeExperimentTypeId obj) : ["run_internal_id" Data.Aeson.Types.ToJSON..= jsonChangeRunExperimentTypeRunInternalId obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["beamtime_id" Data.Aeson.Types.ToJSON..= jsonChangeRunExperimentTypeBeamtimeId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("experiment_type_id" Data.Aeson.Types.ToJSON..=)) (jsonChangeRunExperimentTypeExperimentTypeId obj) : ["run_internal_id" Data.Aeson.Types.ToJSON..= jsonChangeRunExperimentTypeRunInternalId obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonChangeRunExperimentType
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonChangeRunExperimentType" (\obj -> ((GHC.Base.pure JsonChangeRunExperimentType GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtime_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "experiment_type_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "run_internal_id"))}
-- | Create a new 'JsonChangeRunExperimentType' with all required fields.
mkJsonChangeRunExperimentType :: GHC.Types.Int -- ^ 'jsonChangeRunExperimentTypeBeamtimeId'
  -> GHC.Types.Int -- ^ 'jsonChangeRunExperimentTypeRunInternalId'
  -> JsonChangeRunExperimentType
mkJsonChangeRunExperimentType jsonChangeRunExperimentTypeBeamtimeId jsonChangeRunExperimentTypeRunInternalId = JsonChangeRunExperimentType{jsonChangeRunExperimentTypeBeamtimeId = jsonChangeRunExperimentTypeBeamtimeId,
                                                                                                                                           jsonChangeRunExperimentTypeExperimentTypeId = GHC.Maybe.Nothing,
                                                                                                                                           jsonChangeRunExperimentTypeRunInternalId = jsonChangeRunExperimentTypeRunInternalId}
