-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonCreateLiveStreamSnapshotOutput
module AmarcordApi.Types.JsonCreateLiveStreamSnapshotOutput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonCreateLiveStreamSnapshotOutput@ in the specification.
-- 
-- 
data JsonCreateLiveStreamSnapshotOutput = JsonCreateLiveStreamSnapshotOutput {
  -- | description
  jsonCreateLiveStreamSnapshotOutputDescription :: Data.Text.Internal.Text
  -- | file_name
  , jsonCreateLiveStreamSnapshotOutputFileName :: Data.Text.Internal.Text
  -- | id
  , jsonCreateLiveStreamSnapshotOutputId :: GHC.Types.Int
  -- | original_path
  , jsonCreateLiveStreamSnapshotOutputOriginalPath :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | size_in_bytes
  , jsonCreateLiveStreamSnapshotOutputSizeInBytes :: GHC.Types.Int
  -- | type_
  , jsonCreateLiveStreamSnapshotOutputType_ :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonCreateLiveStreamSnapshotOutput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["description" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputDescription obj] : ["file_name" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputFileName obj] : ["id" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("original_path" Data.Aeson.Types.ToJSON..=)) (jsonCreateLiveStreamSnapshotOutputOriginalPath obj) : ["size_in_bytes" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputSizeInBytes obj] : ["type_" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputType_ obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["description" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputDescription obj] : ["file_name" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputFileName obj] : ["id" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("original_path" Data.Aeson.Types.ToJSON..=)) (jsonCreateLiveStreamSnapshotOutputOriginalPath obj) : ["size_in_bytes" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputSizeInBytes obj] : ["type_" Data.Aeson.Types.ToJSON..= jsonCreateLiveStreamSnapshotOutputType_ obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonCreateLiveStreamSnapshotOutput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonCreateLiveStreamSnapshotOutput" (\obj -> (((((GHC.Base.pure JsonCreateLiveStreamSnapshotOutput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "original_path")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "size_in_bytes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type_"))}
-- | Create a new 'JsonCreateLiveStreamSnapshotOutput' with all required fields.
mkJsonCreateLiveStreamSnapshotOutput :: Data.Text.Internal.Text -- ^ 'jsonCreateLiveStreamSnapshotOutputDescription'
  -> Data.Text.Internal.Text -- ^ 'jsonCreateLiveStreamSnapshotOutputFileName'
  -> GHC.Types.Int -- ^ 'jsonCreateLiveStreamSnapshotOutputId'
  -> GHC.Types.Int -- ^ 'jsonCreateLiveStreamSnapshotOutputSizeInBytes'
  -> Data.Text.Internal.Text -- ^ 'jsonCreateLiveStreamSnapshotOutputType_'
  -> JsonCreateLiveStreamSnapshotOutput
mkJsonCreateLiveStreamSnapshotOutput jsonCreateLiveStreamSnapshotOutputDescription jsonCreateLiveStreamSnapshotOutputFileName jsonCreateLiveStreamSnapshotOutputId jsonCreateLiveStreamSnapshotOutputSizeInBytes jsonCreateLiveStreamSnapshotOutputType_ = JsonCreateLiveStreamSnapshotOutput{jsonCreateLiveStreamSnapshotOutputDescription = jsonCreateLiveStreamSnapshotOutputDescription,
                                                                                                                                                                                                                                                                                              jsonCreateLiveStreamSnapshotOutputFileName = jsonCreateLiveStreamSnapshotOutputFileName,
                                                                                                                                                                                                                                                                                              jsonCreateLiveStreamSnapshotOutputId = jsonCreateLiveStreamSnapshotOutputId,
                                                                                                                                                                                                                                                                                              jsonCreateLiveStreamSnapshotOutputOriginalPath = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                              jsonCreateLiveStreamSnapshotOutputSizeInBytes = jsonCreateLiveStreamSnapshotOutputSizeInBytes,
                                                                                                                                                                                                                                                                                              jsonCreateLiveStreamSnapshotOutputType_ = jsonCreateLiveStreamSnapshotOutputType_}
