module AmarcordApi.Types.JsonMergeResultStateQueued where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonMergeResultStateQueued
instance Show JsonMergeResultStateQueued
instance Eq JsonMergeResultStateQueued
instance FromJSON JsonMergeResultStateQueued
instance ToJSON JsonMergeResultStateQueued
