-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonCreateRefinementResultInput
module AmarcordApi.Types.JsonCreateRefinementResultInput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonCreateRefinementResultInput@ in the specification.
-- 
-- 
data JsonCreateRefinementResultInput = JsonCreateRefinementResultInput {
  -- | merge_result_id
  jsonCreateRefinementResultInputMergeResultId :: GHC.Types.Int
  -- | mtz_file_id
  , jsonCreateRefinementResultInputMtzFileId :: GHC.Types.Int
  -- | pdb_file_id
  , jsonCreateRefinementResultInputPdbFileId :: GHC.Types.Int
  -- | r_free
  , jsonCreateRefinementResultInputRFree :: GHC.Types.Double
  -- | r_work
  , jsonCreateRefinementResultInputRWork :: GHC.Types.Double
  -- | rms_bond_angle
  , jsonCreateRefinementResultInputRmsBondAngle :: GHC.Types.Double
  -- | rms_bond_length
  , jsonCreateRefinementResultInputRmsBondLength :: GHC.Types.Double
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonCreateRefinementResultInput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["merge_result_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputMergeResultId obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRmsBondLength obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["merge_result_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputMergeResultId obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= jsonCreateRefinementResultInputRmsBondLength obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonCreateRefinementResultInput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonCreateRefinementResultInput" (\obj -> ((((((GHC.Base.pure JsonCreateRefinementResultInput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "merge_result_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mtz_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pdb_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_free")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_work")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_angle")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_length"))}
-- | Create a new 'JsonCreateRefinementResultInput' with all required fields.
mkJsonCreateRefinementResultInput :: GHC.Types.Int -- ^ 'jsonCreateRefinementResultInputMergeResultId'
  -> GHC.Types.Int -- ^ 'jsonCreateRefinementResultInputMtzFileId'
  -> GHC.Types.Int -- ^ 'jsonCreateRefinementResultInputPdbFileId'
  -> GHC.Types.Double -- ^ 'jsonCreateRefinementResultInputRFree'
  -> GHC.Types.Double -- ^ 'jsonCreateRefinementResultInputRWork'
  -> GHC.Types.Double -- ^ 'jsonCreateRefinementResultInputRmsBondAngle'
  -> GHC.Types.Double -- ^ 'jsonCreateRefinementResultInputRmsBondLength'
  -> JsonCreateRefinementResultInput
mkJsonCreateRefinementResultInput jsonCreateRefinementResultInputMergeResultId jsonCreateRefinementResultInputMtzFileId jsonCreateRefinementResultInputPdbFileId jsonCreateRefinementResultInputRFree jsonCreateRefinementResultInputRWork jsonCreateRefinementResultInputRmsBondAngle jsonCreateRefinementResultInputRmsBondLength = JsonCreateRefinementResultInput{jsonCreateRefinementResultInputMergeResultId = jsonCreateRefinementResultInputMergeResultId,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputMtzFileId = jsonCreateRefinementResultInputMtzFileId,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputPdbFileId = jsonCreateRefinementResultInputPdbFileId,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputRFree = jsonCreateRefinementResultInputRFree,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputRWork = jsonCreateRefinementResultInputRWork,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputRmsBondAngle = jsonCreateRefinementResultInputRmsBondAngle,
                                                                                                                                                                                                                                                                                                                                                                      jsonCreateRefinementResultInputRmsBondLength = jsonCreateRefinementResultInputRmsBondLength}
