-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonDataSet
module AmarcordApi.Types.JsonDataSet where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributoValue
import {-# SOURCE #-} AmarcordApi.Types.JsonIndexingFom

-- | Defines the object schema located at @components.schemas.JsonDataSet@ in the specification.
-- 
-- 
data JsonDataSet = JsonDataSet {
  -- | attributi
  jsonDataSetAttributi :: ([JsonAttributoValue])
  -- | experiment_type_id
  , jsonDataSetExperimentTypeId :: GHC.Types.Int
  -- | id
  , jsonDataSetId :: GHC.Types.Int
  -- | summary
  , jsonDataSetSummary :: (GHC.Maybe.Maybe JsonIndexingFom)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonDataSet
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonDataSetAttributi obj] : ["experiment_type_id" Data.Aeson.Types.ToJSON..= jsonDataSetExperimentTypeId obj] : ["id" Data.Aeson.Types.ToJSON..= jsonDataSetId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("summary" Data.Aeson.Types.ToJSON..=)) (jsonDataSetSummary obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonDataSetAttributi obj] : ["experiment_type_id" Data.Aeson.Types.ToJSON..= jsonDataSetExperimentTypeId obj] : ["id" Data.Aeson.Types.ToJSON..= jsonDataSetId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("summary" Data.Aeson.Types.ToJSON..=)) (jsonDataSetSummary obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonDataSet
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonDataSet" (\obj -> (((GHC.Base.pure JsonDataSet GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "experiment_type_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "summary"))}
-- | Create a new 'JsonDataSet' with all required fields.
mkJsonDataSet :: [JsonAttributoValue] -- ^ 'jsonDataSetAttributi'
  -> GHC.Types.Int -- ^ 'jsonDataSetExperimentTypeId'
  -> GHC.Types.Int -- ^ 'jsonDataSetId'
  -> JsonDataSet
mkJsonDataSet jsonDataSetAttributi jsonDataSetExperimentTypeId jsonDataSetId = JsonDataSet{jsonDataSetAttributi = jsonDataSetAttributi,
                                                                                           jsonDataSetExperimentTypeId = jsonDataSetExperimentTypeId,
                                                                                           jsonDataSetId = jsonDataSetId,
                                                                                           jsonDataSetSummary = GHC.Maybe.Nothing}
