-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonReadBeamtime
module AmarcordApi.Types.JsonReadBeamtime where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonBeamtime

-- | Defines the object schema located at @components.schemas.JsonReadBeamtime@ in the specification.
-- 
-- 
data JsonReadBeamtime = JsonReadBeamtime {
  -- | beamtimes
  jsonReadBeamtimeBeamtimes :: ([JsonBeamtime])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonReadBeamtime
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["beamtimes" Data.Aeson.Types.ToJSON..= jsonReadBeamtimeBeamtimes obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["beamtimes" Data.Aeson.Types.ToJSON..= jsonReadBeamtimeBeamtimes obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonReadBeamtime
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonReadBeamtime" (\obj -> GHC.Base.pure JsonReadBeamtime GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtimes"))}
-- | Create a new 'JsonReadBeamtime' with all required fields.
mkJsonReadBeamtime :: [JsonBeamtime] -- ^ 'jsonReadBeamtimeBeamtimes'
  -> JsonReadBeamtime
mkJsonReadBeamtime jsonReadBeamtimeBeamtimes = JsonReadBeamtime{jsonReadBeamtimeBeamtimes = jsonReadBeamtimeBeamtimes}
