-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonFileOutput
module AmarcordApi.Types.JsonFileOutput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonFileOutput@ in the specification.
-- 
-- 
data JsonFileOutput = JsonFileOutput {
  -- | description
  jsonFileOutputDescription :: Data.Text.Internal.Text
  -- | file_name
  , jsonFileOutputFileName :: Data.Text.Internal.Text
  -- | id
  , jsonFileOutputId :: GHC.Types.Int
  -- | original_path
  , jsonFileOutputOriginalPath :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | size_in_bytes
  , jsonFileOutputSizeInBytes :: GHC.Types.Int
  -- | type_
  , jsonFileOutputType_ :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonFileOutput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["description" Data.Aeson.Types.ToJSON..= jsonFileOutputDescription obj] : ["file_name" Data.Aeson.Types.ToJSON..= jsonFileOutputFileName obj] : ["id" Data.Aeson.Types.ToJSON..= jsonFileOutputId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("original_path" Data.Aeson.Types.ToJSON..=)) (jsonFileOutputOriginalPath obj) : ["size_in_bytes" Data.Aeson.Types.ToJSON..= jsonFileOutputSizeInBytes obj] : ["type_" Data.Aeson.Types.ToJSON..= jsonFileOutputType_ obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["description" Data.Aeson.Types.ToJSON..= jsonFileOutputDescription obj] : ["file_name" Data.Aeson.Types.ToJSON..= jsonFileOutputFileName obj] : ["id" Data.Aeson.Types.ToJSON..= jsonFileOutputId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("original_path" Data.Aeson.Types.ToJSON..=)) (jsonFileOutputOriginalPath obj) : ["size_in_bytes" Data.Aeson.Types.ToJSON..= jsonFileOutputSizeInBytes obj] : ["type_" Data.Aeson.Types.ToJSON..= jsonFileOutputType_ obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonFileOutput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonFileOutput" (\obj -> (((((GHC.Base.pure JsonFileOutput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "original_path")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "size_in_bytes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type_"))}
-- | Create a new 'JsonFileOutput' with all required fields.
mkJsonFileOutput :: Data.Text.Internal.Text -- ^ 'jsonFileOutputDescription'
  -> Data.Text.Internal.Text -- ^ 'jsonFileOutputFileName'
  -> GHC.Types.Int -- ^ 'jsonFileOutputId'
  -> GHC.Types.Int -- ^ 'jsonFileOutputSizeInBytes'
  -> Data.Text.Internal.Text -- ^ 'jsonFileOutputType_'
  -> JsonFileOutput
mkJsonFileOutput jsonFileOutputDescription jsonFileOutputFileName jsonFileOutputId jsonFileOutputSizeInBytes jsonFileOutputType_ = JsonFileOutput{jsonFileOutputDescription = jsonFileOutputDescription,
                                                                                                                                                  jsonFileOutputFileName = jsonFileOutputFileName,
                                                                                                                                                  jsonFileOutputId = jsonFileOutputId,
                                                                                                                                                  jsonFileOutputOriginalPath = GHC.Maybe.Nothing,
                                                                                                                                                  jsonFileOutputSizeInBytes = jsonFileOutputSizeInBytes,
                                                                                                                                                  jsonFileOutputType_ = jsonFileOutputType_}
