-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonReadAnalysisResults
module AmarcordApi.Types.JsonReadAnalysisResults where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAnalysisExperimentType
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributo
import {-# SOURCE #-} AmarcordApi.Types.JsonChemicalIdAndName
import {-# SOURCE #-} AmarcordApi.Types.JsonExperimentType

-- | Defines the object schema located at @components.schemas.JsonReadAnalysisResults@ in the specification.
-- 
-- 
data JsonReadAnalysisResults = JsonReadAnalysisResults {
  -- | attributi
  jsonReadAnalysisResultsAttributi :: ([JsonAttributo])
  -- | chemical_id_to_name
  , jsonReadAnalysisResultsChemicalIdToName :: ([JsonChemicalIdAndName])
  -- | data_sets
  , jsonReadAnalysisResultsDataSets :: ([JsonAnalysisExperimentType])
  -- | experiment_types
  , jsonReadAnalysisResultsExperimentTypes :: ([JsonExperimentType])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonReadAnalysisResults
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsAttributi obj] : ["chemical_id_to_name" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsChemicalIdToName obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsDataSets obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsExperimentTypes obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsAttributi obj] : ["chemical_id_to_name" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsChemicalIdToName obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsDataSets obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadAnalysisResultsExperimentTypes obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonReadAnalysisResults
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonReadAnalysisResults" (\obj -> (((GHC.Base.pure JsonReadAnalysisResults GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemical_id_to_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "data_sets")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "experiment_types"))}
-- | Create a new 'JsonReadAnalysisResults' with all required fields.
mkJsonReadAnalysisResults :: [JsonAttributo] -- ^ 'jsonReadAnalysisResultsAttributi'
  -> [JsonChemicalIdAndName] -- ^ 'jsonReadAnalysisResultsChemicalIdToName'
  -> [JsonAnalysisExperimentType] -- ^ 'jsonReadAnalysisResultsDataSets'
  -> [JsonExperimentType] -- ^ 'jsonReadAnalysisResultsExperimentTypes'
  -> JsonReadAnalysisResults
mkJsonReadAnalysisResults jsonReadAnalysisResultsAttributi jsonReadAnalysisResultsChemicalIdToName jsonReadAnalysisResultsDataSets jsonReadAnalysisResultsExperimentTypes = JsonReadAnalysisResults{jsonReadAnalysisResultsAttributi = jsonReadAnalysisResultsAttributi,
                                                                                                                                                                                                    jsonReadAnalysisResultsChemicalIdToName = jsonReadAnalysisResultsChemicalIdToName,
                                                                                                                                                                                                    jsonReadAnalysisResultsDataSets = jsonReadAnalysisResultsDataSets,
                                                                                                                                                                                                    jsonReadAnalysisResultsExperimentTypes = jsonReadAnalysisResultsExperimentTypes}
