-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonAttributoBulkValue
module AmarcordApi.Types.JsonAttributoBulkValue where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributoValue

-- | Defines the object schema located at @components.schemas.JsonAttributoBulkValue@ in the specification.
-- 
-- 
data JsonAttributoBulkValue = JsonAttributoBulkValue {
  -- | attributo_id
  jsonAttributoBulkValueAttributoId :: GHC.Types.Int
  -- | values
  , jsonAttributoBulkValueValues :: ([JsonAttributoValue])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonAttributoBulkValue
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributo_id" Data.Aeson.Types.ToJSON..= jsonAttributoBulkValueAttributoId obj] : ["values" Data.Aeson.Types.ToJSON..= jsonAttributoBulkValueValues obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributo_id" Data.Aeson.Types.ToJSON..= jsonAttributoBulkValueAttributoId obj] : ["values" Data.Aeson.Types.ToJSON..= jsonAttributoBulkValueValues obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonAttributoBulkValue
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonAttributoBulkValue" (\obj -> (GHC.Base.pure JsonAttributoBulkValue GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributo_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "values"))}
-- | Create a new 'JsonAttributoBulkValue' with all required fields.
mkJsonAttributoBulkValue :: GHC.Types.Int -- ^ 'jsonAttributoBulkValueAttributoId'
  -> [JsonAttributoValue] -- ^ 'jsonAttributoBulkValueValues'
  -> JsonAttributoBulkValue
mkJsonAttributoBulkValue jsonAttributoBulkValueAttributoId jsonAttributoBulkValueValues = JsonAttributoBulkValue{jsonAttributoBulkValueAttributoId = jsonAttributoBulkValueAttributoId,
                                                                                                                 jsonAttributoBulkValueValues = jsonAttributoBulkValueValues}
