-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonCheckStandardUnitOutput
module AmarcordApi.Types.JsonCheckStandardUnitOutput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonCheckStandardUnitOutput@ in the specification.
-- 
-- 
data JsonCheckStandardUnitOutput = JsonCheckStandardUnitOutput {
  -- | error
  jsonCheckStandardUnitOutputError :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | input
  , jsonCheckStandardUnitOutputInput :: Data.Text.Internal.Text
  -- | normalized
  , jsonCheckStandardUnitOutputNormalized :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonCheckStandardUnitOutput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("error" Data.Aeson.Types.ToJSON..=)) (jsonCheckStandardUnitOutputError obj) : ["input" Data.Aeson.Types.ToJSON..= jsonCheckStandardUnitOutputInput obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("normalized" Data.Aeson.Types.ToJSON..=)) (jsonCheckStandardUnitOutputNormalized obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("error" Data.Aeson.Types.ToJSON..=)) (jsonCheckStandardUnitOutputError obj) : ["input" Data.Aeson.Types.ToJSON..= jsonCheckStandardUnitOutputInput obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("normalized" Data.Aeson.Types.ToJSON..=)) (jsonCheckStandardUnitOutputNormalized obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonCheckStandardUnitOutput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonCheckStandardUnitOutput" (\obj -> ((GHC.Base.pure JsonCheckStandardUnitOutput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "error")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "input")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "normalized"))}
-- | Create a new 'JsonCheckStandardUnitOutput' with all required fields.
mkJsonCheckStandardUnitOutput :: Data.Text.Internal.Text -- ^ 'jsonCheckStandardUnitOutputInput'
  -> JsonCheckStandardUnitOutput
mkJsonCheckStandardUnitOutput jsonCheckStandardUnitOutputInput = JsonCheckStandardUnitOutput{jsonCheckStandardUnitOutputError = GHC.Maybe.Nothing,
                                                                                             jsonCheckStandardUnitOutputInput = jsonCheckStandardUnitOutputInput,
                                                                                             jsonCheckStandardUnitOutputNormalized = GHC.Maybe.Nothing}
