module AmarcordApi.Types.JsonCreateAttributiFromSchemaSingleAttributo where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonCreateAttributiFromSchemaSingleAttributo
instance Show JsonCreateAttributiFromSchemaSingleAttributo
instance Eq JsonCreateAttributiFromSchemaSingleAttributo
instance FromJSON JsonCreateAttributiFromSchemaSingleAttributo
instance ToJSON JsonCreateAttributiFromSchemaSingleAttributo
data JsonCreateAttributiFromSchemaSingleAttributoAttributoType'Variants
instance Show JsonCreateAttributiFromSchemaSingleAttributoAttributoType'Variants
instance Eq JsonCreateAttributiFromSchemaSingleAttributoAttributoType'Variants
instance FromJSON JsonCreateAttributiFromSchemaSingleAttributoAttributoType'Variants
instance ToJSON JsonCreateAttributiFromSchemaSingleAttributoAttributoType'Variants
