-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonRefinementResult
module AmarcordApi.Types.JsonRefinementResult where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonRefinementResult@ in the specification.
-- 
-- 
data JsonRefinementResult = JsonRefinementResult {
  -- | id
  jsonRefinementResultId :: GHC.Types.Int
  -- | merge_result_id
  , jsonRefinementResultMergeResultId :: GHC.Types.Int
  -- | mtz_file_id
  , jsonRefinementResultMtzFileId :: GHC.Types.Int
  -- | pdb_file_id
  , jsonRefinementResultPdbFileId :: GHC.Types.Int
  -- | r_free
  , jsonRefinementResultRFree :: GHC.Types.Double
  -- | r_work
  , jsonRefinementResultRWork :: GHC.Types.Double
  -- | rms_bond_angle
  , jsonRefinementResultRmsBondAngle :: GHC.Types.Double
  -- | rms_bond_length
  , jsonRefinementResultRmsBondLength :: GHC.Types.Double
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonRefinementResult
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["id" Data.Aeson.Types.ToJSON..= jsonRefinementResultId obj] : ["merge_result_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultMergeResultId obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= jsonRefinementResultRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= jsonRefinementResultRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= jsonRefinementResultRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= jsonRefinementResultRmsBondLength obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["id" Data.Aeson.Types.ToJSON..= jsonRefinementResultId obj] : ["merge_result_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultMergeResultId obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= jsonRefinementResultPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= jsonRefinementResultRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= jsonRefinementResultRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= jsonRefinementResultRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= jsonRefinementResultRmsBondLength obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonRefinementResult
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonRefinementResult" (\obj -> (((((((GHC.Base.pure JsonRefinementResult GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "merge_result_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mtz_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pdb_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_free")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_work")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_angle")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_length"))}
-- | Create a new 'JsonRefinementResult' with all required fields.
mkJsonRefinementResult :: GHC.Types.Int -- ^ 'jsonRefinementResultId'
  -> GHC.Types.Int -- ^ 'jsonRefinementResultMergeResultId'
  -> GHC.Types.Int -- ^ 'jsonRefinementResultMtzFileId'
  -> GHC.Types.Int -- ^ 'jsonRefinementResultPdbFileId'
  -> GHC.Types.Double -- ^ 'jsonRefinementResultRFree'
  -> GHC.Types.Double -- ^ 'jsonRefinementResultRWork'
  -> GHC.Types.Double -- ^ 'jsonRefinementResultRmsBondAngle'
  -> GHC.Types.Double -- ^ 'jsonRefinementResultRmsBondLength'
  -> JsonRefinementResult
mkJsonRefinementResult jsonRefinementResultId jsonRefinementResultMergeResultId jsonRefinementResultMtzFileId jsonRefinementResultPdbFileId jsonRefinementResultRFree jsonRefinementResultRWork jsonRefinementResultRmsBondAngle jsonRefinementResultRmsBondLength = JsonRefinementResult{jsonRefinementResultId = jsonRefinementResultId,
                                                                                                                                                                                                                                                                                          jsonRefinementResultMergeResultId = jsonRefinementResultMergeResultId,
                                                                                                                                                                                                                                                                                          jsonRefinementResultMtzFileId = jsonRefinementResultMtzFileId,
                                                                                                                                                                                                                                                                                          jsonRefinementResultPdbFileId = jsonRefinementResultPdbFileId,
                                                                                                                                                                                                                                                                                          jsonRefinementResultRFree = jsonRefinementResultRFree,
                                                                                                                                                                                                                                                                                          jsonRefinementResultRWork = jsonRefinementResultRWork,
                                                                                                                                                                                                                                                                                          jsonRefinementResultRmsBondAngle = jsonRefinementResultRmsBondAngle,
                                                                                                                                                                                                                                                                                          jsonRefinementResultRmsBondLength = jsonRefinementResultRmsBondLength}
