-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonIndexingStatistic
module AmarcordApi.Types.JsonIndexingStatistic where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonIndexingStatistic@ in the specification.
-- 
-- 
data JsonIndexingStatistic = JsonIndexingStatistic {
  -- | crystals
  jsonIndexingStatisticCrystals :: GHC.Types.Int
  -- | frames
  , jsonIndexingStatisticFrames :: GHC.Types.Int
  -- | hits
  , jsonIndexingStatisticHits :: GHC.Types.Int
  -- | indexed
  , jsonIndexingStatisticIndexed :: GHC.Types.Int
  -- | time
  , jsonIndexingStatisticTime :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonIndexingStatistic
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["crystals" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticCrystals obj] : ["frames" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticFrames obj] : ["hits" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticHits obj] : ["indexed" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticIndexed obj] : ["time" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticTime obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["crystals" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticCrystals obj] : ["frames" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticFrames obj] : ["hits" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticHits obj] : ["indexed" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticIndexed obj] : ["time" Data.Aeson.Types.ToJSON..= jsonIndexingStatisticTime obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonIndexingStatistic
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonIndexingStatistic" (\obj -> ((((GHC.Base.pure JsonIndexingStatistic GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "crystals")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "frames")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "hits")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "indexed")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "time"))}
-- | Create a new 'JsonIndexingStatistic' with all required fields.
mkJsonIndexingStatistic :: GHC.Types.Int -- ^ 'jsonIndexingStatisticCrystals'
  -> GHC.Types.Int -- ^ 'jsonIndexingStatisticFrames'
  -> GHC.Types.Int -- ^ 'jsonIndexingStatisticHits'
  -> GHC.Types.Int -- ^ 'jsonIndexingStatisticIndexed'
  -> GHC.Types.Int -- ^ 'jsonIndexingStatisticTime'
  -> JsonIndexingStatistic
mkJsonIndexingStatistic jsonIndexingStatisticCrystals jsonIndexingStatisticFrames jsonIndexingStatisticHits jsonIndexingStatisticIndexed jsonIndexingStatisticTime = JsonIndexingStatistic{jsonIndexingStatisticCrystals = jsonIndexingStatisticCrystals,
                                                                                                                                                                                           jsonIndexingStatisticFrames = jsonIndexingStatisticFrames,
                                                                                                                                                                                           jsonIndexingStatisticHits = jsonIndexingStatisticHits,
                                                                                                                                                                                           jsonIndexingStatisticIndexed = jsonIndexingStatisticIndexed,
                                                                                                                                                                                           jsonIndexingStatisticTime = jsonIndexingStatisticTime}
