module AmarcordApi.Types.JsonCreateLiveStreamSnapshotOutput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonCreateLiveStreamSnapshotOutput
instance Show JsonCreateLiveStreamSnapshotOutput
instance Eq JsonCreateLiveStreamSnapshotOutput
instance FromJSON JsonCreateLiveStreamSnapshotOutput
instance ToJSON JsonCreateLiveStreamSnapshotOutput
