-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonUpdateAttributoInput
module AmarcordApi.Types.JsonUpdateAttributoInput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributo
import {-# SOURCE #-} AmarcordApi.Types.JsonUpdateAttributoConversionFlags

-- | Defines the object schema located at @components.schemas.JsonUpdateAttributoInput@ in the specification.
-- 
-- 
data JsonUpdateAttributoInput = JsonUpdateAttributoInput {
  -- | attributo
  jsonUpdateAttributoInputAttributo :: JsonAttributo
  -- | beamtime_id
  , jsonUpdateAttributoInputBeamtimeId :: GHC.Types.Int
  -- | conversion_flags
  , jsonUpdateAttributoInputConversionFlags :: JsonUpdateAttributoConversionFlags
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonUpdateAttributoInput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributo" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputAttributo obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputBeamtimeId obj] : ["conversion_flags" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputConversionFlags obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributo" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputAttributo obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputBeamtimeId obj] : ["conversion_flags" Data.Aeson.Types.ToJSON..= jsonUpdateAttributoInputConversionFlags obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonUpdateAttributoInput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonUpdateAttributoInput" (\obj -> ((GHC.Base.pure JsonUpdateAttributoInput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributo")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtime_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "conversion_flags"))}
-- | Create a new 'JsonUpdateAttributoInput' with all required fields.
mkJsonUpdateAttributoInput :: JsonAttributo -- ^ 'jsonUpdateAttributoInputAttributo'
  -> GHC.Types.Int -- ^ 'jsonUpdateAttributoInputBeamtimeId'
  -> JsonUpdateAttributoConversionFlags -- ^ 'jsonUpdateAttributoInputConversionFlags'
  -> JsonUpdateAttributoInput
mkJsonUpdateAttributoInput jsonUpdateAttributoInputAttributo jsonUpdateAttributoInputBeamtimeId jsonUpdateAttributoInputConversionFlags = JsonUpdateAttributoInput{jsonUpdateAttributoInputAttributo = jsonUpdateAttributoInputAttributo,
                                                                                                                                                                   jsonUpdateAttributoInputBeamtimeId = jsonUpdateAttributoInputBeamtimeId,
                                                                                                                                                                   jsonUpdateAttributoInputConversionFlags = jsonUpdateAttributoInputConversionFlags}
