module AmarcordApi.Types.JsonDeleteExperimentType where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonDeleteExperimentType
instance Show JsonDeleteExperimentType
instance Eq JsonDeleteExperimentType
instance FromJSON JsonDeleteExperimentType
instance ToJSON JsonDeleteExperimentType
