-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonExperimentType
module AmarcordApi.Types.JsonExperimentType where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributiIdAndRole

-- | Defines the object schema located at @components.schemas.JsonExperimentType@ in the specification.
-- 
-- 
data JsonExperimentType = JsonExperimentType {
  -- | attributi
  jsonExperimentTypeAttributi :: ([JsonAttributiIdAndRole])
  -- | id
  , jsonExperimentTypeId :: GHC.Types.Int
  -- | name
  , jsonExperimentTypeName :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonExperimentType
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonExperimentTypeAttributi obj] : ["id" Data.Aeson.Types.ToJSON..= jsonExperimentTypeId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonExperimentTypeName obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonExperimentTypeAttributi obj] : ["id" Data.Aeson.Types.ToJSON..= jsonExperimentTypeId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonExperimentTypeName obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonExperimentType
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonExperimentType" (\obj -> ((GHC.Base.pure JsonExperimentType GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name"))}
-- | Create a new 'JsonExperimentType' with all required fields.
mkJsonExperimentType :: [JsonAttributiIdAndRole] -- ^ 'jsonExperimentTypeAttributi'
  -> GHC.Types.Int -- ^ 'jsonExperimentTypeId'
  -> Data.Text.Internal.Text -- ^ 'jsonExperimentTypeName'
  -> JsonExperimentType
mkJsonExperimentType jsonExperimentTypeAttributi jsonExperimentTypeId jsonExperimentTypeName = JsonExperimentType{jsonExperimentTypeAttributi = jsonExperimentTypeAttributi,
                                                                                                                  jsonExperimentTypeId = jsonExperimentTypeId,
                                                                                                                  jsonExperimentTypeName = jsonExperimentTypeName}
