-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonReadRuns
module AmarcordApi.Types.JsonReadRuns where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributo
import {-# SOURCE #-} AmarcordApi.Types.JsonChemical
import {-# SOURCE #-} AmarcordApi.Types.JsonDataSet
import {-# SOURCE #-} AmarcordApi.Types.JsonEvent
import {-# SOURCE #-} AmarcordApi.Types.JsonExperimentType
import {-# SOURCE #-} AmarcordApi.Types.JsonRun
import {-# SOURCE #-} AmarcordApi.Types.JsonUserConfig

-- | Defines the object schema located at @components.schemas.JsonReadRuns@ in the specification.
-- 
-- 
data JsonReadRuns = JsonReadRuns {
  -- | attributi
  jsonReadRunsAttributi :: ([JsonAttributo])
  -- | chemicals
  , jsonReadRunsChemicals :: ([JsonChemical])
  -- | data_sets
  , jsonReadRunsDataSets :: ([JsonDataSet])
  -- | events
  , jsonReadRunsEvents :: ([JsonEvent])
  -- | experiment_types
  , jsonReadRunsExperimentTypes :: ([JsonExperimentType])
  -- | filter_dates
  , jsonReadRunsFilterDates :: ([Data.Text.Internal.Text])
  -- | live_stream_file_id
  , jsonReadRunsLiveStreamFileId :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | runs
  , jsonReadRunsRuns :: ([JsonRun])
  -- | user_config
  , jsonReadRunsUserConfig :: JsonUserConfig
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonReadRuns
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadRunsAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadRunsChemicals obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadRunsDataSets obj] : ["events" Data.Aeson.Types.ToJSON..= jsonReadRunsEvents obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadRunsExperimentTypes obj] : ["filter_dates" Data.Aeson.Types.ToJSON..= jsonReadRunsFilterDates obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("live_stream_file_id" Data.Aeson.Types.ToJSON..=)) (jsonReadRunsLiveStreamFileId obj) : ["runs" Data.Aeson.Types.ToJSON..= jsonReadRunsRuns obj] : ["user_config" Data.Aeson.Types.ToJSON..= jsonReadRunsUserConfig obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadRunsAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadRunsChemicals obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadRunsDataSets obj] : ["events" Data.Aeson.Types.ToJSON..= jsonReadRunsEvents obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadRunsExperimentTypes obj] : ["filter_dates" Data.Aeson.Types.ToJSON..= jsonReadRunsFilterDates obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("live_stream_file_id" Data.Aeson.Types.ToJSON..=)) (jsonReadRunsLiveStreamFileId obj) : ["runs" Data.Aeson.Types.ToJSON..= jsonReadRunsRuns obj] : ["user_config" Data.Aeson.Types.ToJSON..= jsonReadRunsUserConfig obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonReadRuns
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonReadRuns" (\obj -> ((((((((GHC.Base.pure JsonReadRuns GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemicals")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "data_sets")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "events")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "experiment_types")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "filter_dates")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "live_stream_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "runs")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "user_config"))}
-- | Create a new 'JsonReadRuns' with all required fields.
mkJsonReadRuns :: [JsonAttributo] -- ^ 'jsonReadRunsAttributi'
  -> [JsonChemical] -- ^ 'jsonReadRunsChemicals'
  -> [JsonDataSet] -- ^ 'jsonReadRunsDataSets'
  -> [JsonEvent] -- ^ 'jsonReadRunsEvents'
  -> [JsonExperimentType] -- ^ 'jsonReadRunsExperimentTypes'
  -> [Data.Text.Internal.Text] -- ^ 'jsonReadRunsFilterDates'
  -> [JsonRun] -- ^ 'jsonReadRunsRuns'
  -> JsonUserConfig -- ^ 'jsonReadRunsUserConfig'
  -> JsonReadRuns
mkJsonReadRuns jsonReadRunsAttributi jsonReadRunsChemicals jsonReadRunsDataSets jsonReadRunsEvents jsonReadRunsExperimentTypes jsonReadRunsFilterDates jsonReadRunsRuns jsonReadRunsUserConfig = JsonReadRuns{jsonReadRunsAttributi = jsonReadRunsAttributi,
                                                                                                                                                                                                              jsonReadRunsChemicals = jsonReadRunsChemicals,
                                                                                                                                                                                                              jsonReadRunsDataSets = jsonReadRunsDataSets,
                                                                                                                                                                                                              jsonReadRunsEvents = jsonReadRunsEvents,
                                                                                                                                                                                                              jsonReadRunsExperimentTypes = jsonReadRunsExperimentTypes,
                                                                                                                                                                                                              jsonReadRunsFilterDates = jsonReadRunsFilterDates,
                                                                                                                                                                                                              jsonReadRunsLiveStreamFileId = GHC.Maybe.Nothing,
                                                                                                                                                                                                              jsonReadRunsRuns = jsonReadRunsRuns,
                                                                                                                                                                                                              jsonReadRunsUserConfig = jsonReadRunsUserConfig}
