module AmarcordApi.Types.JsonCreateAttributiFromSchemaOutput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonCreateAttributiFromSchemaOutput
instance Show JsonCreateAttributiFromSchemaOutput
instance Eq JsonCreateAttributiFromSchemaOutput
instance FromJSON JsonCreateAttributiFromSchemaOutput
instance ToJSON JsonCreateAttributiFromSchemaOutput
