-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonMergeResultRootJson
module AmarcordApi.Types.JsonMergeResultRootJson where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.MergeResult

-- | Defines the object schema located at @components.schemas.JsonMergeResultRootJson@ in the specification.
-- 
-- 
data JsonMergeResultRootJson = JsonMergeResultRootJson {
  -- | error
  jsonMergeResultRootJsonError :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | result
  , jsonMergeResultRootJsonResult :: (GHC.Maybe.Maybe MergeResult)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonMergeResultRootJson
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("error" Data.Aeson.Types.ToJSON..=)) (jsonMergeResultRootJsonError obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("result" Data.Aeson.Types.ToJSON..=)) (jsonMergeResultRootJsonResult obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("error" Data.Aeson.Types.ToJSON..=)) (jsonMergeResultRootJsonError obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("result" Data.Aeson.Types.ToJSON..=)) (jsonMergeResultRootJsonResult obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonMergeResultRootJson
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonMergeResultRootJson" (\obj -> (GHC.Base.pure JsonMergeResultRootJson GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "error")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "result"))}
-- | Create a new 'JsonMergeResultRootJson' with all required fields.
mkJsonMergeResultRootJson :: JsonMergeResultRootJson
mkJsonMergeResultRootJson = JsonMergeResultRootJson{jsonMergeResultRootJsonError = GHC.Maybe.Nothing,
                                                    jsonMergeResultRootJsonResult = GHC.Maybe.Nothing}
