module AmarcordApi.Types.JsonDeleteChemicalInput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonDeleteChemicalInput
instance Show JsonDeleteChemicalInput
instance Eq JsonDeleteChemicalInput
instance FromJSON JsonDeleteChemicalInput
instance ToJSON JsonDeleteChemicalInput
