module AmarcordApi.Types.JsonUpdateRunsBulkOutput where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonUpdateRunsBulkOutput
instance Show JsonUpdateRunsBulkOutput
instance Eq JsonUpdateRunsBulkOutput
instance FromJSON JsonUpdateRunsBulkOutput
instance ToJSON JsonUpdateRunsBulkOutput
