-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonMergeResultStateRunning
module AmarcordApi.Types.JsonMergeResultStateRunning where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonMergeResultStateRunning@ in the specification.
-- 
-- 
data JsonMergeResultStateRunning = JsonMergeResultStateRunning {
  -- | job_id
  jsonMergeResultStateRunningJobId :: GHC.Types.Int
  -- | latest_log
  , jsonMergeResultStateRunningLatestLog :: Data.Text.Internal.Text
  -- | started
  , jsonMergeResultStateRunningStarted :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonMergeResultStateRunning
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["job_id" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningJobId obj] : ["latest_log" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningLatestLog obj] : ["started" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningStarted obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["job_id" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningJobId obj] : ["latest_log" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningLatestLog obj] : ["started" Data.Aeson.Types.ToJSON..= jsonMergeResultStateRunningStarted obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonMergeResultStateRunning
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonMergeResultStateRunning" (\obj -> ((GHC.Base.pure JsonMergeResultStateRunning GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "job_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "latest_log")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "started"))}
-- | Create a new 'JsonMergeResultStateRunning' with all required fields.
mkJsonMergeResultStateRunning :: GHC.Types.Int -- ^ 'jsonMergeResultStateRunningJobId'
  -> Data.Text.Internal.Text -- ^ 'jsonMergeResultStateRunningLatestLog'
  -> GHC.Types.Int -- ^ 'jsonMergeResultStateRunningStarted'
  -> JsonMergeResultStateRunning
mkJsonMergeResultStateRunning jsonMergeResultStateRunningJobId jsonMergeResultStateRunningLatestLog jsonMergeResultStateRunningStarted = JsonMergeResultStateRunning{jsonMergeResultStateRunningJobId = jsonMergeResultStateRunningJobId,
                                                                                                                                                                     jsonMergeResultStateRunningLatestLog = jsonMergeResultStateRunningLatestLog,
                                                                                                                                                                     jsonMergeResultStateRunningStarted = jsonMergeResultStateRunningStarted}
