-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonReadRunAnalysis
module AmarcordApi.Types.JsonReadRunAnalysis where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAnalysisRun
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributo
import {-# SOURCE #-} AmarcordApi.Types.JsonChemical
import {-# SOURCE #-} AmarcordApi.Types.JsonRunAnalysisIndexingResult

-- | Defines the object schema located at @components.schemas.JsonReadRunAnalysis@ in the specification.
-- 
-- 
data JsonReadRunAnalysis = JsonReadRunAnalysis {
  -- | attributi
  jsonReadRunAnalysisAttributi :: ([JsonAttributo])
  -- | chemicals
  , jsonReadRunAnalysisChemicals :: ([JsonChemical])
  -- | indexing_results_by_run_id
  , jsonReadRunAnalysisIndexingResultsByRunId :: ([JsonRunAnalysisIndexingResult])
  -- | runs
  , jsonReadRunAnalysisRuns :: ([JsonAnalysisRun])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonReadRunAnalysis
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisChemicals obj] : ["indexing_results_by_run_id" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisIndexingResultsByRunId obj] : ["runs" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisRuns obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisChemicals obj] : ["indexing_results_by_run_id" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisIndexingResultsByRunId obj] : ["runs" Data.Aeson.Types.ToJSON..= jsonReadRunAnalysisRuns obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonReadRunAnalysis
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonReadRunAnalysis" (\obj -> (((GHC.Base.pure JsonReadRunAnalysis GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemicals")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "indexing_results_by_run_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "runs"))}
-- | Create a new 'JsonReadRunAnalysis' with all required fields.
mkJsonReadRunAnalysis :: [JsonAttributo] -- ^ 'jsonReadRunAnalysisAttributi'
  -> [JsonChemical] -- ^ 'jsonReadRunAnalysisChemicals'
  -> [JsonRunAnalysisIndexingResult] -- ^ 'jsonReadRunAnalysisIndexingResultsByRunId'
  -> [JsonAnalysisRun] -- ^ 'jsonReadRunAnalysisRuns'
  -> JsonReadRunAnalysis
mkJsonReadRunAnalysis jsonReadRunAnalysisAttributi jsonReadRunAnalysisChemicals jsonReadRunAnalysisIndexingResultsByRunId jsonReadRunAnalysisRuns = JsonReadRunAnalysis{jsonReadRunAnalysisAttributi = jsonReadRunAnalysisAttributi,
                                                                                                                                                                        jsonReadRunAnalysisChemicals = jsonReadRunAnalysisChemicals,
                                                                                                                                                                        jsonReadRunAnalysisIndexingResultsByRunId = jsonReadRunAnalysisIndexingResultsByRunId,
                                                                                                                                                                        jsonReadRunAnalysisRuns = jsonReadRunAnalysisRuns}
