module AmarcordApi.Types.JsonReadExperimentTypes where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonReadExperimentTypes
instance Show JsonReadExperimentTypes
instance Eq JsonReadExperimentTypes
instance FromJSON JsonReadExperimentTypes
instance ToJSON JsonReadExperimentTypes
