-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonCreateDataSetFromRun
module AmarcordApi.Types.JsonCreateDataSetFromRun where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonCreateDataSetFromRun@ in the specification.
-- 
-- 
data JsonCreateDataSetFromRun = JsonCreateDataSetFromRun {
  -- | beamtime_id
  jsonCreateDataSetFromRunBeamtimeId :: GHC.Types.Int
  -- | experiment_type_id
  , jsonCreateDataSetFromRunExperimentTypeId :: GHC.Types.Int
  -- | run_internal_id
  , jsonCreateDataSetFromRunRunInternalId :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonCreateDataSetFromRun
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["beamtime_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunBeamtimeId obj] : ["experiment_type_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunExperimentTypeId obj] : ["run_internal_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunRunInternalId obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["beamtime_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunBeamtimeId obj] : ["experiment_type_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunExperimentTypeId obj] : ["run_internal_id" Data.Aeson.Types.ToJSON..= jsonCreateDataSetFromRunRunInternalId obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonCreateDataSetFromRun
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonCreateDataSetFromRun" (\obj -> ((GHC.Base.pure JsonCreateDataSetFromRun GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtime_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "experiment_type_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "run_internal_id"))}
-- | Create a new 'JsonCreateDataSetFromRun' with all required fields.
mkJsonCreateDataSetFromRun :: GHC.Types.Int -- ^ 'jsonCreateDataSetFromRunBeamtimeId'
  -> GHC.Types.Int -- ^ 'jsonCreateDataSetFromRunExperimentTypeId'
  -> GHC.Types.Int -- ^ 'jsonCreateDataSetFromRunRunInternalId'
  -> JsonCreateDataSetFromRun
mkJsonCreateDataSetFromRun jsonCreateDataSetFromRunBeamtimeId jsonCreateDataSetFromRunExperimentTypeId jsonCreateDataSetFromRunRunInternalId = JsonCreateDataSetFromRun{jsonCreateDataSetFromRunBeamtimeId = jsonCreateDataSetFromRunBeamtimeId,
                                                                                                                                                                        jsonCreateDataSetFromRunExperimentTypeId = jsonCreateDataSetFromRunExperimentTypeId,
                                                                                                                                                                        jsonCreateDataSetFromRunRunInternalId = jsonCreateDataSetFromRunRunInternalId}
