-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonReadDataSets
module AmarcordApi.Types.JsonReadDataSets where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributo
import {-# SOURCE #-} AmarcordApi.Types.JsonChemical
import {-# SOURCE #-} AmarcordApi.Types.JsonDataSet
import {-# SOURCE #-} AmarcordApi.Types.JsonExperimentType

-- | Defines the object schema located at @components.schemas.JsonReadDataSets@ in the specification.
-- 
-- 
data JsonReadDataSets = JsonReadDataSets {
  -- | attributi
  jsonReadDataSetsAttributi :: ([JsonAttributo])
  -- | chemicals
  , jsonReadDataSetsChemicals :: ([JsonChemical])
  -- | data_sets
  , jsonReadDataSetsDataSets :: ([JsonDataSet])
  -- | experiment_types
  , jsonReadDataSetsExperimentTypes :: ([JsonExperimentType])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonReadDataSets
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadDataSetsAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadDataSetsChemicals obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadDataSetsDataSets obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadDataSetsExperimentTypes obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonReadDataSetsAttributi obj] : ["chemicals" Data.Aeson.Types.ToJSON..= jsonReadDataSetsChemicals obj] : ["data_sets" Data.Aeson.Types.ToJSON..= jsonReadDataSetsDataSets obj] : ["experiment_types" Data.Aeson.Types.ToJSON..= jsonReadDataSetsExperimentTypes obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonReadDataSets
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonReadDataSets" (\obj -> (((GHC.Base.pure JsonReadDataSets GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemicals")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "data_sets")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "experiment_types"))}
-- | Create a new 'JsonReadDataSets' with all required fields.
mkJsonReadDataSets :: [JsonAttributo] -- ^ 'jsonReadDataSetsAttributi'
  -> [JsonChemical] -- ^ 'jsonReadDataSetsChemicals'
  -> [JsonDataSet] -- ^ 'jsonReadDataSetsDataSets'
  -> [JsonExperimentType] -- ^ 'jsonReadDataSetsExperimentTypes'
  -> JsonReadDataSets
mkJsonReadDataSets jsonReadDataSetsAttributi jsonReadDataSetsChemicals jsonReadDataSetsDataSets jsonReadDataSetsExperimentTypes = JsonReadDataSets{jsonReadDataSetsAttributi = jsonReadDataSetsAttributi,
                                                                                                                                                   jsonReadDataSetsChemicals = jsonReadDataSetsChemicals,
                                                                                                                                                   jsonReadDataSetsDataSets = jsonReadDataSetsDataSets,
                                                                                                                                                   jsonReadDataSetsExperimentTypes = jsonReadDataSetsExperimentTypes}
