-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonAttributo
module AmarcordApi.Types.JsonAttributo where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.AssociatedTable
import {-# SOURCE #-} AmarcordApi.Types.JSONSchemaArray
import {-# SOURCE #-} AmarcordApi.Types.JSONSchemaBoolean
import {-# SOURCE #-} AmarcordApi.Types.JSONSchemaInteger
import {-# SOURCE #-} AmarcordApi.Types.JSONSchemaNumber
import {-# SOURCE #-} AmarcordApi.Types.JSONSchemaString

-- | Defines the object schema located at @components.schemas.JsonAttributo@ in the specification.
-- 
-- 
data JsonAttributo = JsonAttributo {
  -- | associated_table: An enumeration.
  jsonAttributoAssociatedTable :: AssociatedTable
  -- | attributo_type_array
  , jsonAttributoAttributoTypeArray :: (GHC.Maybe.Maybe JSONSchemaArray)
  -- | attributo_type_boolean
  , jsonAttributoAttributoTypeBoolean :: (GHC.Maybe.Maybe JSONSchemaBoolean)
  -- | attributo_type_integer
  , jsonAttributoAttributoTypeInteger :: (GHC.Maybe.Maybe JSONSchemaInteger)
  -- | attributo_type_number
  , jsonAttributoAttributoTypeNumber :: (GHC.Maybe.Maybe JSONSchemaNumber)
  -- | attributo_type_string
  , jsonAttributoAttributoTypeString :: (GHC.Maybe.Maybe JSONSchemaString)
  -- | description
  , jsonAttributoDescription :: Data.Text.Internal.Text
  -- | group
  , jsonAttributoGroup :: Data.Text.Internal.Text
  -- | id
  , jsonAttributoId :: GHC.Types.Int
  -- | name
  , jsonAttributoName :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonAttributo
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["associated_table" Data.Aeson.Types.ToJSON..= jsonAttributoAssociatedTable obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_array" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeArray obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_boolean" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeBoolean obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_integer" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeInteger obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_number" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeNumber obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_string" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeString obj) : ["description" Data.Aeson.Types.ToJSON..= jsonAttributoDescription obj] : ["group" Data.Aeson.Types.ToJSON..= jsonAttributoGroup obj] : ["id" Data.Aeson.Types.ToJSON..= jsonAttributoId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonAttributoName obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["associated_table" Data.Aeson.Types.ToJSON..= jsonAttributoAssociatedTable obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_array" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeArray obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_boolean" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeBoolean obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_integer" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeInteger obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_number" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeNumber obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributo_type_string" Data.Aeson.Types.ToJSON..=)) (jsonAttributoAttributoTypeString obj) : ["description" Data.Aeson.Types.ToJSON..= jsonAttributoDescription obj] : ["group" Data.Aeson.Types.ToJSON..= jsonAttributoGroup obj] : ["id" Data.Aeson.Types.ToJSON..= jsonAttributoId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonAttributoName obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonAttributo
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonAttributo" (\obj -> (((((((((GHC.Base.pure JsonAttributo GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "associated_table")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributo_type_array")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributo_type_boolean")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributo_type_integer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributo_type_number")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributo_type_string")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "group")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name"))}
-- | Create a new 'JsonAttributo' with all required fields.
mkJsonAttributo :: AssociatedTable -- ^ 'jsonAttributoAssociatedTable'
  -> Data.Text.Internal.Text -- ^ 'jsonAttributoDescription'
  -> Data.Text.Internal.Text -- ^ 'jsonAttributoGroup'
  -> GHC.Types.Int -- ^ 'jsonAttributoId'
  -> Data.Text.Internal.Text -- ^ 'jsonAttributoName'
  -> JsonAttributo
mkJsonAttributo jsonAttributoAssociatedTable jsonAttributoDescription jsonAttributoGroup jsonAttributoId jsonAttributoName = JsonAttributo{jsonAttributoAssociatedTable = jsonAttributoAssociatedTable,
                                                                                                                                           jsonAttributoAttributoTypeArray = GHC.Maybe.Nothing,
                                                                                                                                           jsonAttributoAttributoTypeBoolean = GHC.Maybe.Nothing,
                                                                                                                                           jsonAttributoAttributoTypeInteger = GHC.Maybe.Nothing,
                                                                                                                                           jsonAttributoAttributoTypeNumber = GHC.Maybe.Nothing,
                                                                                                                                           jsonAttributoAttributoTypeString = GHC.Maybe.Nothing,
                                                                                                                                           jsonAttributoDescription = jsonAttributoDescription,
                                                                                                                                           jsonAttributoGroup = jsonAttributoGroup,
                                                                                                                                           jsonAttributoId = jsonAttributoId,
                                                                                                                                           jsonAttributoName = jsonAttributoName}
