-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonIndexingFom
module AmarcordApi.Types.JsonIndexingFom where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonIndexingFom@ in the specification.
-- 
-- 
data JsonIndexingFom = JsonIndexingFom {
  -- | detector_shift_x_mm
  jsonIndexingFomDetectorShiftXMm :: (GHC.Maybe.Maybe GHC.Types.Double)
  -- | detector_shift_y_mm
  , jsonIndexingFomDetectorShiftYMm :: (GHC.Maybe.Maybe GHC.Types.Double)
  -- | hit_rate
  , jsonIndexingFomHitRate :: GHC.Types.Double
  -- | indexed_frames
  , jsonIndexingFomIndexedFrames :: GHC.Types.Int
  -- | indexing_rate
  , jsonIndexingFomIndexingRate :: GHC.Types.Double
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonIndexingFom
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("detector_shift_x_mm" Data.Aeson.Types.ToJSON..=)) (jsonIndexingFomDetectorShiftXMm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("detector_shift_y_mm" Data.Aeson.Types.ToJSON..=)) (jsonIndexingFomDetectorShiftYMm obj) : ["hit_rate" Data.Aeson.Types.ToJSON..= jsonIndexingFomHitRate obj] : ["indexed_frames" Data.Aeson.Types.ToJSON..= jsonIndexingFomIndexedFrames obj] : ["indexing_rate" Data.Aeson.Types.ToJSON..= jsonIndexingFomIndexingRate obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("detector_shift_x_mm" Data.Aeson.Types.ToJSON..=)) (jsonIndexingFomDetectorShiftXMm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("detector_shift_y_mm" Data.Aeson.Types.ToJSON..=)) (jsonIndexingFomDetectorShiftYMm obj) : ["hit_rate" Data.Aeson.Types.ToJSON..= jsonIndexingFomHitRate obj] : ["indexed_frames" Data.Aeson.Types.ToJSON..= jsonIndexingFomIndexedFrames obj] : ["indexing_rate" Data.Aeson.Types.ToJSON..= jsonIndexingFomIndexingRate obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonIndexingFom
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonIndexingFom" (\obj -> ((((GHC.Base.pure JsonIndexingFom GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "detector_shift_x_mm")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "detector_shift_y_mm")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "hit_rate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "indexed_frames")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "indexing_rate"))}
-- | Create a new 'JsonIndexingFom' with all required fields.
mkJsonIndexingFom :: GHC.Types.Double -- ^ 'jsonIndexingFomHitRate'
  -> GHC.Types.Int -- ^ 'jsonIndexingFomIndexedFrames'
  -> GHC.Types.Double -- ^ 'jsonIndexingFomIndexingRate'
  -> JsonIndexingFom
mkJsonIndexingFom jsonIndexingFomHitRate jsonIndexingFomIndexedFrames jsonIndexingFomIndexingRate = JsonIndexingFom{jsonIndexingFomDetectorShiftXMm = GHC.Maybe.Nothing,
                                                                                                                    jsonIndexingFomDetectorShiftYMm = GHC.Maybe.Nothing,
                                                                                                                    jsonIndexingFomHitRate = jsonIndexingFomHitRate,
                                                                                                                    jsonIndexingFomIndexedFrames = jsonIndexingFomIndexedFrames,
                                                                                                                    jsonIndexingFomIndexingRate = jsonIndexingFomIndexingRate}
