module AmarcordApi.Types.JsonRunAnalysisIndexingResult where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonRunAnalysisIndexingResult
instance Show JsonRunAnalysisIndexingResult
instance Eq JsonRunAnalysisIndexingResult
instance FromJSON JsonRunAnalysisIndexingResult
instance ToJSON JsonRunAnalysisIndexingResult
