-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JSONSchemaInteger
module AmarcordApi.Types.JSONSchemaInteger where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JSONSchemaInteger@ in the specification.
-- 
-- 
data JSONSchemaInteger = JSONSchemaInteger {
  -- | format
  jSONSchemaIntegerFormat :: (GHC.Maybe.Maybe JSONSchemaIntegerFormat')
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JSONSchemaInteger
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (jSONSchemaIntegerFormat obj) : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "integer"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (jSONSchemaIntegerFormat obj) : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "integer"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JSONSchemaInteger
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JSONSchemaInteger" (\obj -> GHC.Base.pure JSONSchemaInteger GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "format"))}
-- | Create a new 'JSONSchemaInteger' with all required fields.
mkJSONSchemaInteger :: JSONSchemaInteger
mkJSONSchemaInteger = JSONSchemaInteger{jSONSchemaIntegerFormat = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.JSONSchemaInteger.properties.format@ in the specification.
-- 
-- 
data JSONSchemaIntegerFormat' =
   JSONSchemaIntegerFormat'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | JSONSchemaIntegerFormat'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | JSONSchemaIntegerFormat'EnumDateTime -- ^ Represents the JSON value @"date-time"@
  | JSONSchemaIntegerFormat'EnumChemicalId -- ^ Represents the JSON value @"chemical-id"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JSONSchemaIntegerFormat'
    where {toJSON (JSONSchemaIntegerFormat'Other val) = val;
           toJSON (JSONSchemaIntegerFormat'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (JSONSchemaIntegerFormat'EnumDateTime) = "date-time";
           toJSON (JSONSchemaIntegerFormat'EnumChemicalId) = "chemical-id"}
instance Data.Aeson.Types.FromJSON.FromJSON JSONSchemaIntegerFormat'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "date-time" -> JSONSchemaIntegerFormat'EnumDateTime
                                             | val GHC.Classes.== "chemical-id" -> JSONSchemaIntegerFormat'EnumChemicalId
                                             | GHC.Base.otherwise -> JSONSchemaIntegerFormat'Other val)}
