module AmarcordApi.Types.JsonMergeResultRootJson where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonMergeResultRootJson
instance Show JsonMergeResultRootJson
instance Eq JsonMergeResultRootJson
instance FromJSON JsonMergeResultRootJson
instance ToJSON JsonMergeResultRootJson
