-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonMergeResultStateError
module AmarcordApi.Types.JsonMergeResultStateError where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonMergeResultStateError@ in the specification.
-- 
-- 
data JsonMergeResultStateError = JsonMergeResultStateError {
  -- | error
  jsonMergeResultStateErrorError :: Data.Text.Internal.Text
  -- | latest_log
  , jsonMergeResultStateErrorLatestLog :: Data.Text.Internal.Text
  -- | started
  , jsonMergeResultStateErrorStarted :: GHC.Types.Int
  -- | stopped
  , jsonMergeResultStateErrorStopped :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonMergeResultStateError
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["error" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorError obj] : ["latest_log" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorLatestLog obj] : ["started" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorStarted obj] : ["stopped" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorStopped obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["error" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorError obj] : ["latest_log" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorLatestLog obj] : ["started" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorStarted obj] : ["stopped" Data.Aeson.Types.ToJSON..= jsonMergeResultStateErrorStopped obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonMergeResultStateError
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonMergeResultStateError" (\obj -> (((GHC.Base.pure JsonMergeResultStateError GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "error")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "latest_log")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "started")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "stopped"))}
-- | Create a new 'JsonMergeResultStateError' with all required fields.
mkJsonMergeResultStateError :: Data.Text.Internal.Text -- ^ 'jsonMergeResultStateErrorError'
  -> Data.Text.Internal.Text -- ^ 'jsonMergeResultStateErrorLatestLog'
  -> GHC.Types.Int -- ^ 'jsonMergeResultStateErrorStarted'
  -> GHC.Types.Int -- ^ 'jsonMergeResultStateErrorStopped'
  -> JsonMergeResultStateError
mkJsonMergeResultStateError jsonMergeResultStateErrorError jsonMergeResultStateErrorLatestLog jsonMergeResultStateErrorStarted jsonMergeResultStateErrorStopped = JsonMergeResultStateError{jsonMergeResultStateErrorError = jsonMergeResultStateErrorError,
                                                                                                                                                                                            jsonMergeResultStateErrorLatestLog = jsonMergeResultStateErrorLatestLog,
                                                                                                                                                                                            jsonMergeResultStateErrorStarted = jsonMergeResultStateErrorStarted,
                                                                                                                                                                                            jsonMergeResultStateErrorStopped = jsonMergeResultStateErrorStopped}
