-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonChemical
module AmarcordApi.Types.JsonChemical where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.ChemicalType
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributoValue
import {-# SOURCE #-} AmarcordApi.Types.JsonFileOutput

-- | Defines the object schema located at @components.schemas.JsonChemical@ in the specification.
-- 
-- 
data JsonChemical = JsonChemical {
  -- | attributi
  jsonChemicalAttributi :: ([JsonAttributoValue])
  -- | beamtime_id
  , jsonChemicalBeamtimeId :: GHC.Types.Int
  -- | chemical_type: An enumeration.
  , jsonChemicalChemicalType :: ChemicalType
  -- | files
  , jsonChemicalFiles :: ([JsonFileOutput])
  -- | id
  , jsonChemicalId :: GHC.Types.Int
  -- | name
  , jsonChemicalName :: Data.Text.Internal.Text
  -- | responsible_person
  , jsonChemicalResponsiblePerson :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonChemical
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonChemicalAttributi obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonChemicalBeamtimeId obj] : ["chemical_type" Data.Aeson.Types.ToJSON..= jsonChemicalChemicalType obj] : ["files" Data.Aeson.Types.ToJSON..= jsonChemicalFiles obj] : ["id" Data.Aeson.Types.ToJSON..= jsonChemicalId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonChemicalName obj] : ["responsible_person" Data.Aeson.Types.ToJSON..= jsonChemicalResponsiblePerson obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonChemicalAttributi obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonChemicalBeamtimeId obj] : ["chemical_type" Data.Aeson.Types.ToJSON..= jsonChemicalChemicalType obj] : ["files" Data.Aeson.Types.ToJSON..= jsonChemicalFiles obj] : ["id" Data.Aeson.Types.ToJSON..= jsonChemicalId obj] : ["name" Data.Aeson.Types.ToJSON..= jsonChemicalName obj] : ["responsible_person" Data.Aeson.Types.ToJSON..= jsonChemicalResponsiblePerson obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonChemical
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonChemical" (\obj -> ((((((GHC.Base.pure JsonChemical GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtime_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chemical_type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "files")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "responsible_person"))}
-- | Create a new 'JsonChemical' with all required fields.
mkJsonChemical :: [JsonAttributoValue] -- ^ 'jsonChemicalAttributi'
  -> GHC.Types.Int -- ^ 'jsonChemicalBeamtimeId'
  -> ChemicalType -- ^ 'jsonChemicalChemicalType'
  -> [JsonFileOutput] -- ^ 'jsonChemicalFiles'
  -> GHC.Types.Int -- ^ 'jsonChemicalId'
  -> Data.Text.Internal.Text -- ^ 'jsonChemicalName'
  -> Data.Text.Internal.Text -- ^ 'jsonChemicalResponsiblePerson'
  -> JsonChemical
mkJsonChemical jsonChemicalAttributi jsonChemicalBeamtimeId jsonChemicalChemicalType jsonChemicalFiles jsonChemicalId jsonChemicalName jsonChemicalResponsiblePerson = JsonChemical{jsonChemicalAttributi = jsonChemicalAttributi,
                                                                                                                                                                                    jsonChemicalBeamtimeId = jsonChemicalBeamtimeId,
                                                                                                                                                                                    jsonChemicalChemicalType = jsonChemicalChemicalType,
                                                                                                                                                                                    jsonChemicalFiles = jsonChemicalFiles,
                                                                                                                                                                                    jsonChemicalId = jsonChemicalId,
                                                                                                                                                                                    jsonChemicalName = jsonChemicalName,
                                                                                                                                                                                    jsonChemicalResponsiblePerson = jsonChemicalResponsiblePerson}
