module AmarcordApi.Types.JsonAnalysisExperimentType where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified AmarcordApi.Common
data JsonAnalysisExperimentType
instance Show JsonAnalysisExperimentType
instance Eq JsonAnalysisExperimentType
instance FromJSON JsonAnalysisExperimentType
instance ToJSON JsonAnalysisExperimentType
