-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonUpdateBeamtimeInput
module AmarcordApi.Types.JsonUpdateBeamtimeInput where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.JsonUpdateBeamtimeInput@ in the specification.
-- 
-- 
data JsonUpdateBeamtimeInput = JsonUpdateBeamtimeInput {
  -- | beamline
  jsonUpdateBeamtimeInputBeamline :: Data.Text.Internal.Text
  -- | comment
  , jsonUpdateBeamtimeInputComment :: Data.Text.Internal.Text
  -- | end
  , jsonUpdateBeamtimeInputEnd :: GHC.Types.Int
  -- | external_id
  , jsonUpdateBeamtimeInputExternalId :: Data.Text.Internal.Text
  -- | id
  , jsonUpdateBeamtimeInputId :: GHC.Types.Int
  -- | proposal
  , jsonUpdateBeamtimeInputProposal :: Data.Text.Internal.Text
  -- | start
  , jsonUpdateBeamtimeInputStart :: GHC.Types.Int
  -- | title
  , jsonUpdateBeamtimeInputTitle :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonUpdateBeamtimeInput
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["beamline" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputBeamline obj] : ["comment" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputComment obj] : ["end" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputEnd obj] : ["external_id" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputExternalId obj] : ["id" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputId obj] : ["proposal" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputProposal obj] : ["start" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputStart obj] : ["title" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputTitle obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["beamline" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputBeamline obj] : ["comment" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputComment obj] : ["end" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputEnd obj] : ["external_id" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputExternalId obj] : ["id" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputId obj] : ["proposal" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputProposal obj] : ["start" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputStart obj] : ["title" Data.Aeson.Types.ToJSON..= jsonUpdateBeamtimeInputTitle obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonUpdateBeamtimeInput
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonUpdateBeamtimeInput" (\obj -> (((((((GHC.Base.pure JsonUpdateBeamtimeInput GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamline")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "comment")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "end")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "external_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "proposal")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "start")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "title"))}
-- | Create a new 'JsonUpdateBeamtimeInput' with all required fields.
mkJsonUpdateBeamtimeInput :: Data.Text.Internal.Text -- ^ 'jsonUpdateBeamtimeInputBeamline'
  -> Data.Text.Internal.Text -- ^ 'jsonUpdateBeamtimeInputComment'
  -> GHC.Types.Int -- ^ 'jsonUpdateBeamtimeInputEnd'
  -> Data.Text.Internal.Text -- ^ 'jsonUpdateBeamtimeInputExternalId'
  -> GHC.Types.Int -- ^ 'jsonUpdateBeamtimeInputId'
  -> Data.Text.Internal.Text -- ^ 'jsonUpdateBeamtimeInputProposal'
  -> GHC.Types.Int -- ^ 'jsonUpdateBeamtimeInputStart'
  -> Data.Text.Internal.Text -- ^ 'jsonUpdateBeamtimeInputTitle'
  -> JsonUpdateBeamtimeInput
mkJsonUpdateBeamtimeInput jsonUpdateBeamtimeInputBeamline jsonUpdateBeamtimeInputComment jsonUpdateBeamtimeInputEnd jsonUpdateBeamtimeInputExternalId jsonUpdateBeamtimeInputId jsonUpdateBeamtimeInputProposal jsonUpdateBeamtimeInputStart jsonUpdateBeamtimeInputTitle = JsonUpdateBeamtimeInput{jsonUpdateBeamtimeInputBeamline = jsonUpdateBeamtimeInputBeamline,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputComment = jsonUpdateBeamtimeInputComment,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputEnd = jsonUpdateBeamtimeInputEnd,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputExternalId = jsonUpdateBeamtimeInputExternalId,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputId = jsonUpdateBeamtimeInputId,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputProposal = jsonUpdateBeamtimeInputProposal,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputStart = jsonUpdateBeamtimeInputStart,
                                                                                                                                                                                                                                                                                                    jsonUpdateBeamtimeInputTitle = jsonUpdateBeamtimeInputTitle}
