-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema JsonCreateOrUpdateRun
module AmarcordApi.Types.JsonCreateOrUpdateRun where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.JsonAttributoValue

-- | Defines the object schema located at @components.schemas.JsonCreateOrUpdateRun@ in the specification.
-- 
-- 
data JsonCreateOrUpdateRun = JsonCreateOrUpdateRun {
  -- | attributi
  jsonCreateOrUpdateRunAttributi :: ([JsonAttributoValue])
  -- | beamtime_id
  , jsonCreateOrUpdateRunBeamtimeId :: GHC.Types.Int
  -- | started
  , jsonCreateOrUpdateRunStarted :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | stopped
  , jsonCreateOrUpdateRunStopped :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON JsonCreateOrUpdateRun
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonCreateOrUpdateRunAttributi obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonCreateOrUpdateRunBeamtimeId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("started" Data.Aeson.Types.ToJSON..=)) (jsonCreateOrUpdateRunStarted obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("stopped" Data.Aeson.Types.ToJSON..=)) (jsonCreateOrUpdateRunStopped obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["attributi" Data.Aeson.Types.ToJSON..= jsonCreateOrUpdateRunAttributi obj] : ["beamtime_id" Data.Aeson.Types.ToJSON..= jsonCreateOrUpdateRunBeamtimeId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("started" Data.Aeson.Types.ToJSON..=)) (jsonCreateOrUpdateRunStarted obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("stopped" Data.Aeson.Types.ToJSON..=)) (jsonCreateOrUpdateRunStopped obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON JsonCreateOrUpdateRun
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "JsonCreateOrUpdateRun" (\obj -> (((GHC.Base.pure JsonCreateOrUpdateRun GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "attributi")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "beamtime_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "started")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "stopped"))}
-- | Create a new 'JsonCreateOrUpdateRun' with all required fields.
mkJsonCreateOrUpdateRun :: [JsonAttributoValue] -- ^ 'jsonCreateOrUpdateRunAttributi'
  -> GHC.Types.Int -- ^ 'jsonCreateOrUpdateRunBeamtimeId'
  -> JsonCreateOrUpdateRun
mkJsonCreateOrUpdateRun jsonCreateOrUpdateRunAttributi jsonCreateOrUpdateRunBeamtimeId = JsonCreateOrUpdateRun{jsonCreateOrUpdateRunAttributi = jsonCreateOrUpdateRunAttributi,
                                                                                                               jsonCreateOrUpdateRunBeamtimeId = jsonCreateOrUpdateRunBeamtimeId,
                                                                                                               jsonCreateOrUpdateRunStarted = GHC.Maybe.Nothing,
                                                                                                               jsonCreateOrUpdateRunStopped = GHC.Maybe.Nothing}
