-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema MergeResultShell
module AmarcordApi.Types.MergeResultShell where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.MergeResultShell@ in the specification.
-- 
-- 
data MergeResultShell = MergeResultShell {
  -- | cc
  mergeResultShellCc :: GHC.Types.Double
  -- | ccstar
  , mergeResultShellCcstar :: GHC.Types.Double
  -- | completeness
  , mergeResultShellCompleteness :: GHC.Types.Double
  -- | d_over_a
  , mergeResultShellDOverA :: GHC.Types.Double
  -- | max_res
  , mergeResultShellMaxRes :: GHC.Types.Double
  -- | mean_i
  , mergeResultShellMeanI :: GHC.Types.Double
  -- | measurements
  , mergeResultShellMeasurements :: GHC.Types.Int
  -- | min_res
  , mergeResultShellMinRes :: GHC.Types.Double
  -- | nref
  , mergeResultShellNref :: GHC.Types.Int
  -- | one_over_d_centre
  , mergeResultShellOneOverDCentre :: GHC.Types.Double
  -- | r_split
  , mergeResultShellRSplit :: GHC.Types.Double
  -- | redundancy
  , mergeResultShellRedundancy :: GHC.Types.Double
  -- | reflections_possible
  , mergeResultShellReflectionsPossible :: GHC.Types.Int
  -- | snr
  , mergeResultShellSnr :: GHC.Types.Double
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MergeResultShell
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["cc" Data.Aeson.Types.ToJSON..= mergeResultShellCc obj] : ["ccstar" Data.Aeson.Types.ToJSON..= mergeResultShellCcstar obj] : ["completeness" Data.Aeson.Types.ToJSON..= mergeResultShellCompleteness obj] : ["d_over_a" Data.Aeson.Types.ToJSON..= mergeResultShellDOverA obj] : ["max_res" Data.Aeson.Types.ToJSON..= mergeResultShellMaxRes obj] : ["mean_i" Data.Aeson.Types.ToJSON..= mergeResultShellMeanI obj] : ["measurements" Data.Aeson.Types.ToJSON..= mergeResultShellMeasurements obj] : ["min_res" Data.Aeson.Types.ToJSON..= mergeResultShellMinRes obj] : ["nref" Data.Aeson.Types.ToJSON..= mergeResultShellNref obj] : ["one_over_d_centre" Data.Aeson.Types.ToJSON..= mergeResultShellOneOverDCentre obj] : ["r_split" Data.Aeson.Types.ToJSON..= mergeResultShellRSplit obj] : ["redundancy" Data.Aeson.Types.ToJSON..= mergeResultShellRedundancy obj] : ["reflections_possible" Data.Aeson.Types.ToJSON..= mergeResultShellReflectionsPossible obj] : ["snr" Data.Aeson.Types.ToJSON..= mergeResultShellSnr obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["cc" Data.Aeson.Types.ToJSON..= mergeResultShellCc obj] : ["ccstar" Data.Aeson.Types.ToJSON..= mergeResultShellCcstar obj] : ["completeness" Data.Aeson.Types.ToJSON..= mergeResultShellCompleteness obj] : ["d_over_a" Data.Aeson.Types.ToJSON..= mergeResultShellDOverA obj] : ["max_res" Data.Aeson.Types.ToJSON..= mergeResultShellMaxRes obj] : ["mean_i" Data.Aeson.Types.ToJSON..= mergeResultShellMeanI obj] : ["measurements" Data.Aeson.Types.ToJSON..= mergeResultShellMeasurements obj] : ["min_res" Data.Aeson.Types.ToJSON..= mergeResultShellMinRes obj] : ["nref" Data.Aeson.Types.ToJSON..= mergeResultShellNref obj] : ["one_over_d_centre" Data.Aeson.Types.ToJSON..= mergeResultShellOneOverDCentre obj] : ["r_split" Data.Aeson.Types.ToJSON..= mergeResultShellRSplit obj] : ["redundancy" Data.Aeson.Types.ToJSON..= mergeResultShellRedundancy obj] : ["reflections_possible" Data.Aeson.Types.ToJSON..= mergeResultShellReflectionsPossible obj] : ["snr" Data.Aeson.Types.ToJSON..= mergeResultShellSnr obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MergeResultShell
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MergeResultShell" (\obj -> (((((((((((((GHC.Base.pure MergeResultShell GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "cc")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "ccstar")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "completeness")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "d_over_a")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "max_res")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mean_i")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "measurements")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "min_res")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "nref")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "one_over_d_centre")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_split")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "redundancy")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "reflections_possible")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "snr"))}
-- | Create a new 'MergeResultShell' with all required fields.
mkMergeResultShell :: GHC.Types.Double -- ^ 'mergeResultShellCc'
  -> GHC.Types.Double -- ^ 'mergeResultShellCcstar'
  -> GHC.Types.Double -- ^ 'mergeResultShellCompleteness'
  -> GHC.Types.Double -- ^ 'mergeResultShellDOverA'
  -> GHC.Types.Double -- ^ 'mergeResultShellMaxRes'
  -> GHC.Types.Double -- ^ 'mergeResultShellMeanI'
  -> GHC.Types.Int -- ^ 'mergeResultShellMeasurements'
  -> GHC.Types.Double -- ^ 'mergeResultShellMinRes'
  -> GHC.Types.Int -- ^ 'mergeResultShellNref'
  -> GHC.Types.Double -- ^ 'mergeResultShellOneOverDCentre'
  -> GHC.Types.Double -- ^ 'mergeResultShellRSplit'
  -> GHC.Types.Double -- ^ 'mergeResultShellRedundancy'
  -> GHC.Types.Int -- ^ 'mergeResultShellReflectionsPossible'
  -> GHC.Types.Double -- ^ 'mergeResultShellSnr'
  -> MergeResultShell
mkMergeResultShell mergeResultShellCc mergeResultShellCcstar mergeResultShellCompleteness mergeResultShellDOverA mergeResultShellMaxRes mergeResultShellMeanI mergeResultShellMeasurements mergeResultShellMinRes mergeResultShellNref mergeResultShellOneOverDCentre mergeResultShellRSplit mergeResultShellRedundancy mergeResultShellReflectionsPossible mergeResultShellSnr = MergeResultShell{mergeResultShellCc = mergeResultShellCc,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellCcstar = mergeResultShellCcstar,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellCompleteness = mergeResultShellCompleteness,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellDOverA = mergeResultShellDOverA,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellMaxRes = mergeResultShellMaxRes,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellMeanI = mergeResultShellMeanI,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellMeasurements = mergeResultShellMeasurements,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellMinRes = mergeResultShellMinRes,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellNref = mergeResultShellNref,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellOneOverDCentre = mergeResultShellOneOverDCentre,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellRSplit = mergeResultShellRSplit,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellRedundancy = mergeResultShellRedundancy,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellReflectionsPossible = mergeResultShellReflectionsPossible,
                                                                                                                                                                                                                                                                                                                                                                                                   mergeResultShellSnr = mergeResultShellSnr}
