-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema MergeResult
module AmarcordApi.Types.MergeResult where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias
import {-# SOURCE #-} AmarcordApi.Types.MergeResultFom
import {-# SOURCE #-} AmarcordApi.Types.MergeResultShell
import {-# SOURCE #-} AmarcordApi.Types.RefinementResult

-- | Defines the object schema located at @components.schemas.MergeResult@ in the specification.
-- 
-- 
data MergeResult = MergeResult {
  -- | detailed_foms
  mergeResultDetailedFoms :: ([MergeResultShell])
  -- | fom
  , mergeResultFom :: MergeResultFom
  -- | mtz_file_id
  , mergeResultMtzFileId :: GHC.Types.Int
  -- | refinement_results
  , mergeResultRefinementResults :: ([RefinementResult])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MergeResult
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["detailed_foms" Data.Aeson.Types.ToJSON..= mergeResultDetailedFoms obj] : ["fom" Data.Aeson.Types.ToJSON..= mergeResultFom obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= mergeResultMtzFileId obj] : ["refinement_results" Data.Aeson.Types.ToJSON..= mergeResultRefinementResults obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["detailed_foms" Data.Aeson.Types.ToJSON..= mergeResultDetailedFoms obj] : ["fom" Data.Aeson.Types.ToJSON..= mergeResultFom obj] : ["mtz_file_id" Data.Aeson.Types.ToJSON..= mergeResultMtzFileId obj] : ["refinement_results" Data.Aeson.Types.ToJSON..= mergeResultRefinementResults obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MergeResult
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MergeResult" (\obj -> (((GHC.Base.pure MergeResult GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "detailed_foms")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "fom")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mtz_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "refinement_results"))}
-- | Create a new 'MergeResult' with all required fields.
mkMergeResult :: [MergeResultShell] -- ^ 'mergeResultDetailedFoms'
  -> MergeResultFom -- ^ 'mergeResultFom'
  -> GHC.Types.Int -- ^ 'mergeResultMtzFileId'
  -> [RefinementResult] -- ^ 'mergeResultRefinementResults'
  -> MergeResult
mkMergeResult mergeResultDetailedFoms mergeResultFom mergeResultMtzFileId mergeResultRefinementResults = MergeResult{mergeResultDetailedFoms = mergeResultDetailedFoms,
                                                                                                                     mergeResultFom = mergeResultFom,
                                                                                                                     mergeResultMtzFileId = mergeResultMtzFileId,
                                                                                                                     mergeResultRefinementResults = mergeResultRefinementResults}
