-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema RefinementResult
module AmarcordApi.Types.RefinementResult where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified AmarcordApi.Common
import AmarcordApi.TypeAlias

-- | Defines the object schema located at @components.schemas.RefinementResult@ in the specification.
-- 
-- 
data RefinementResult = RefinementResult {
  -- | mtz_file_id
  refinementResultMtzFileId :: GHC.Types.Int
  -- | pdb_file_id
  , refinementResultPdbFileId :: GHC.Types.Int
  -- | r_free
  , refinementResultRFree :: GHC.Types.Double
  -- | r_work
  , refinementResultRWork :: GHC.Types.Double
  -- | rms_bond_angle
  , refinementResultRmsBondAngle :: GHC.Types.Double
  -- | rms_bond_length
  , refinementResultRmsBondLength :: GHC.Types.Double
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON RefinementResult
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["mtz_file_id" Data.Aeson.Types.ToJSON..= refinementResultMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= refinementResultPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= refinementResultRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= refinementResultRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= refinementResultRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= refinementResultRmsBondLength obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["mtz_file_id" Data.Aeson.Types.ToJSON..= refinementResultMtzFileId obj] : ["pdb_file_id" Data.Aeson.Types.ToJSON..= refinementResultPdbFileId obj] : ["r_free" Data.Aeson.Types.ToJSON..= refinementResultRFree obj] : ["r_work" Data.Aeson.Types.ToJSON..= refinementResultRWork obj] : ["rms_bond_angle" Data.Aeson.Types.ToJSON..= refinementResultRmsBondAngle obj] : ["rms_bond_length" Data.Aeson.Types.ToJSON..= refinementResultRmsBondLength obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON RefinementResult
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "RefinementResult" (\obj -> (((((GHC.Base.pure RefinementResult GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mtz_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pdb_file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_free")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "r_work")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_angle")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rms_bond_length"))}
-- | Create a new 'RefinementResult' with all required fields.
mkRefinementResult :: GHC.Types.Int -- ^ 'refinementResultMtzFileId'
  -> GHC.Types.Int -- ^ 'refinementResultPdbFileId'
  -> GHC.Types.Double -- ^ 'refinementResultRFree'
  -> GHC.Types.Double -- ^ 'refinementResultRWork'
  -> GHC.Types.Double -- ^ 'refinementResultRmsBondAngle'
  -> GHC.Types.Double -- ^ 'refinementResultRmsBondLength'
  -> RefinementResult
mkRefinementResult refinementResultMtzFileId refinementResultPdbFileId refinementResultRFree refinementResultRWork refinementResultRmsBondAngle refinementResultRmsBondLength = RefinementResult{refinementResultMtzFileId = refinementResultMtzFileId,
                                                                                                                                                                                                 refinementResultPdbFileId = refinementResultPdbFileId,
                                                                                                                                                                                                 refinementResultRFree = refinementResultRFree,
                                                                                                                                                                                                 refinementResultRWork = refinementResultRWork,
                                                                                                                                                                                                 refinementResultRmsBondAngle = refinementResultRmsBondAngle,
                                                                                                                                                                                                 refinementResultRmsBondLength = refinementResultRmsBondLength}
