-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation createRefinementResultApiRefinementResultsPost
module AmarcordApi.Operations.CreateRefinementResultApiRefinementResultsPost where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified AmarcordApi.Common
import AmarcordApi.Types

-- | > POST /api/refinement-results
-- 
-- Create Refinement Result
createRefinementResultApiRefinementResultsPost :: forall m . AmarcordApi.Common.MonadHTTP m => JsonCreateRefinementResultInput -- ^ The request body to send
  -> AmarcordApi.Common.ClientT m (Network.HTTP.Client.Types.Response CreateRefinementResultApiRefinementResultsPostResponse) -- ^ Monadic computation which returns the result of the operation
createRefinementResultApiRefinementResultsPost body = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either CreateRefinementResultApiRefinementResultsPostResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> CreateRefinementResultApiRefinementResultsPostResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             JsonCreateRefinementResultOutput)
                                                                                                                                                                                                                               | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 422) (Network.HTTP.Client.Types.responseStatus response) -> CreateRefinementResultApiRefinementResultsPostResponse422 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             HTTPValidationError)
                                                                                                                                                                                                                               | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (AmarcordApi.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "POST") "/api/refinement-results" GHC.Base.mempty (GHC.Maybe.Just body) AmarcordApi.Common.RequestBodyEncodingJSON)
-- | Represents a response of the operation 'createRefinementResultApiRefinementResultsPost'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'CreateRefinementResultApiRefinementResultsPostResponseError' is used.
data CreateRefinementResultApiRefinementResultsPostResponse =
   CreateRefinementResultApiRefinementResultsPostResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | CreateRefinementResultApiRefinementResultsPostResponse200 JsonCreateRefinementResultOutput -- ^ Successful Response
  | CreateRefinementResultApiRefinementResultsPostResponse422 HTTPValidationError -- ^ Validation Error
  deriving (GHC.Show.Show, GHC.Classes.Eq)
